import { Link } from "react-router-dom";
import { FiUsers, FiStar, FiUserCheck, FiMapPin, FiArrowUpRight } from "react-icons/fi";
import { useMembers, DataNotice } from "../components/MemberData";
import MemberTable from "../components/MemberTable";
export default function Dashboard() {
  const { members, loading, error } = useMembers();
  const premium = members.filter(m => m.isPremium).length;
  const stats = [["Total members", members.length, FiUsers, "rose"], ["Premium members", premium, FiStar, "gold"], ["Standard members", members.length - premium, FiUserCheck, "green"], ["Districts represented", new Set(members.map(m => m.district).filter(Boolean)).size, FiMapPin, "blue"]];
  return <><div className="page-heading"><div><p className="eyebrow">NAMAKKAL MATRIMONY</p><h1>Overview</h1><p className="muted">Your community, at a glance.</p></div><Link className="button primary" to="/members"><FiUsers />View members</Link></div><DataNotice /><div className="stats-grid">{stats.map(([title, value, Icon, color]) => <div className="stat" key={title}><div className={`stat-icon ${color}`}><Icon /></div><span>{title}</span><strong>{loading || error ? "--" : value.toLocaleString()}</strong><small>Current member records</small></div>)}</div>
    <div className="overview-grid"><section className="panel"><div className="section-heading"><h2>Membership mix</h2><FiStar /></div><div className="membership-total"><strong>{loading || error ? "--" : members.length}</strong><span>Total profiles</span></div><div className="mix-bar"><div style={{ width: `${members.length ? premium / members.length * 100 : 0}%` }} /></div><div className="legend"><span><i className="dot premium" />Premium <strong>{loading || error ? "--" : premium}</strong></span><span><i className="dot" />Standard <strong>{loading || error ? "--" : members.length - premium}</strong></span></div></section><section className="panel"><div className="section-heading"><h2>Community breakdown</h2><FiUsers /></div>{["Male", "Female", "Other"].map(gender => { const count = members.filter(m => gender === "Other" ? !["male", "female"].includes(String(m.gender).toLowerCase()) : String(m.gender).toLowerCase() === gender.toLowerCase()).length; return <div className="breakdown" key={gender}><div><span>{gender === "Other" ? "Other / unspecified" : gender}</span><strong>{loading || error ? "--" : count}</strong></div><progress max={members.length || 1} value={count} /></div>; })}</section></div><section className="panel"><div className="section-heading"><div><h2>Member directory</h2><p className="muted">A snapshot of your community</p></div><Link className="text-link" to="/members">View all <FiArrowUpRight /></Link></div><MemberTable members={members.slice(0, 5)} loading={loading} error={error} /></section></>;
}
