import { useEffect, useRef, useState } from "react";
import { FiSearch, FiRefreshCw, FiDownload, FiX, FiChevronLeft, FiChevronRight } from "react-icons/fi";
import { useMembers, DataNotice } from "../components/MemberData";
import MemberTable from "../components/MemberTable";
import { exportMembers } from "../services/export";
function ProfileDialog({ member, close }) {
  const ref = useRef(null);
  useEffect(() => { const previous = document.activeElement; ref.current.showModal(); return () => previous?.focus(); }, []);
  return <dialog ref={ref} className="profile-dialog" aria-label="Member profile" onCancel={close} onClick={e => { if (e.target === e.currentTarget) close(); }}><div className="section-heading"><h2>{member.name || "Member profile"}</h2><button autoFocus className="icon-button" aria-label="Close profile" title="Close profile" onClick={close}><FiX /></button></div><dl className="profile-details">{[["Email", member.email], ["Phone", member.phone || member.mobile], ["Age", member.age], ["Gender", member.gender], ["District", member.district], ["Religion", member.religion], ["Membership", member.isPremium ? "Premium" : "Standard"]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "Not provided"}</dd></div>)}</dl></dialog>;
}
export default function Members({ premiumOnly = false }) {
  const { members, loading, error, refresh } = useMembers();
  const [query, setQuery] = useState(""); const [gender, setGender] = useState(""); const [plan, setPlan] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState(null);
  const filtered = members.filter(m => (!premiumOnly || m.isPremium) && (!plan || (plan === "premium" ? m.isPremium : !m.isPremium)) && (!gender || String(m.gender).toLowerCase() === gender) && [m.name, m.email, m.district, m.religion].some(value => String(value || "").toLowerCase().includes(query.toLowerCase())));
  const pages = Math.max(1, Math.ceil(filtered.length / 10)); const currentPage = Math.min(page, pages);
  function change(setter, value) { setter(value); setPage(1); }
  return <><div className="page-heading"><div><p className="eyebrow">COMMUNITY</p><h1>{premiumOnly ? "Premium members" : "Members"}</h1><p className="muted">{premiumOnly ? "Your premium member directory." : "Browse and review member profiles."}</p></div><button className="button" disabled={loading || !!error || !filtered.length} onClick={() => exportMembers(filtered)}><FiDownload />Export CSV</button></div><DataNotice /><section className="panel directory"><div className="toolbar"><label className="search-input"><FiSearch /><input aria-label="Search members" placeholder="Search name, email or district" value={query} onChange={e => change(setQuery, e.target.value)} /></label><select aria-label="Filter by gender" value={gender} onChange={e => change(setGender, e.target.value)}><option value="">All genders</option><option value="male">Male</option><option value="female">Female</option></select>{!premiumOnly && <select aria-label="Filter by membership" value={plan} onChange={e => change(setPlan, e.target.value)}><option value="">All memberships</option><option value="standard">Standard</option><option value="premium">Premium</option></select>}<button className="icon-button" title="Refresh members" aria-label="Refresh members" disabled={loading} onClick={refresh}><FiRefreshCw /></button></div><MemberTable members={filtered.slice((currentPage - 1) * 10, currentPage * 10)} loading={loading} error={error} onSelect={setSelected} /><div className="pagination"><span>{filtered.length ? (currentPage - 1) * 10 + 1 : 0}-{Math.min(currentPage * 10, filtered.length)} of {filtered.length} members</span><div><button className="icon-button" title="Previous page" aria-label="Previous page" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}><FiChevronLeft /></button><span>{currentPage} / {pages}</span><button className="icon-button" title="Next page" aria-label="Next page" disabled={currentPage === pages} onClick={() => setPage(currentPage + 1)}><FiChevronRight /></button></div></div></section>{selected && <ProfileDialog member={selected} close={() => setSelected(null)} />}</>;
}
