import { useState } from "react";
import { FiSearch, FiRefreshCw, FiDownload, FiChevronLeft, FiChevronRight, FiUserPlus } from "react-icons/fi";
import { useMembers, DataNotice } from "../components/MemberData";
import MemberTable from "../components/MemberTable";
import MemberEditor, { Modal, DeleteMember } from "../components/MemberEditor";
import { exportMembers } from "../services/export";
import { useLanguage } from "../Language";
export default function Members({ premiumOnly = false }) {
  const { t } = useLanguage(); const { members, loading, error, refresh } = useMembers();
  const [query, setQuery] = useState(""); const [gender, setGender] = useState(""); const [plan, setPlan] = useState(""); const [page, setPage] = useState(1);
  const [dialog, setDialog] = useState(null); const [notice, setNotice] = useState("");
  const filtered = members.filter(m => m.role !== "admin" && (!premiumOnly || m.isPremium) && (!plan || (plan === "premium" ? m.isPremium : !m.isPremium)) && (!gender || String(m.gender).toLowerCase() === gender) && [m.name, m.email, m.district, m.religion].some(value => String(value || "").toLowerCase().includes(query.toLowerCase())));
  const pages = Math.max(1, Math.ceil(filtered.length / 10)); const currentPage = Math.min(page, pages);
  function change(setter, value) { setter(value); setPage(1); }
  function complete(message) { setDialog(null); setNotice(message); refresh(); }
  const selected = dialog?.member;
  return <><div className="page-heading"><div><p className="eyebrow">{t("COMMUNITY")}</p><h1>{t(premiumOnly ? "Premium members" : "Members")}</h1><p className="muted">{t(premiumOnly ? "Your premium member directory." : "Browse and review member profiles.")}</p></div><div className="heading-actions"><button className="button" disabled={loading || !!error || !filtered.length} onClick={() => exportMembers(filtered)}><FiDownload />{t("Export CSV")}</button><button className="button primary" onClick={() => { setNotice(""); setDialog({ mode: "add" }); }}><FiUserPlus />{t("Add member")}</button></div></div>
    {notice && <p className="notice success" role="status">{t(notice)}</p>}<DataNotice /><section className="panel directory"><div className="toolbar"><label className="search-input"><FiSearch /><input aria-label={t("Search members")} placeholder={t("Search name, email or district")} value={query} onChange={e => change(setQuery, e.target.value)} /></label><select aria-label={t("Filter by gender")} value={gender} onChange={e => change(setGender, e.target.value)}>{[["", "All genders"], ["male", "Male"], ["female", "Female"]].map(([value, label]) => <option key={value} value={value}>{t(label)}</option>)}</select>{!premiumOnly && <select aria-label={t("Filter by membership")} value={plan} onChange={e => change(setPlan, e.target.value)}>{[["", "All memberships"], ["standard", "Standard"], ["premium", "Premium"]].map(([value, label]) => <option key={value} value={value}>{t(label)}</option>)}</select>}<button className="icon-button" title={t("Refresh members")} aria-label={t("Refresh members")} disabled={loading} onClick={refresh}><FiRefreshCw /></button></div>
    <MemberTable members={filtered.slice((currentPage - 1) * 10, currentPage * 10)} loading={loading} error={error} onSelect={member => setDialog({ mode: "view", member })} onEdit={member => setDialog({ mode: "edit", member })} onDelete={member => setDialog({ mode: "delete", member })} />
    <div className="pagination"><span>{filtered.length ? (currentPage - 1) * 10 + 1 : 0}-{Math.min(currentPage * 10, filtered.length)} {t("of")} {filtered.length} {t("members")}</span><div><button className="icon-button" title={t("Previous page")} aria-label={t("Previous page")} disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}><FiChevronLeft /></button><span>{currentPage} / {pages}</span><button className="icon-button" title={t("Next page")} aria-label={t("Next page")} disabled={currentPage === pages} onClick={() => setPage(currentPage + 1)}><FiChevronRight /></button></div></div></section>
    {dialog?.mode === "view" && <Modal title={selected.name || t("Member profile")} close={() => setDialog(null)}><dl className="profile-details">{[["Email", selected.email], ["Phone", selected.mobile || selected.phone], ["Age", selected.age], ["Gender", t(selected.gender)], ["District", selected.district], ["Religion", selected.religion], ["Membership", t(selected.isPremium ? "Premium" : "Standard")]].map(([label, value]) => <div key={label}><dt>{t(label)}</dt><dd>{value || t("Not provided")}</dd></div>)}</dl></Modal>}
    {["add", "edit"].includes(dialog?.mode) && <MemberEditor member={selected} close={() => setDialog(null)} complete={complete} />}{dialog?.mode === "delete" && <DeleteMember member={selected} close={() => setDialog(null)} complete={complete} />}
  </>;
}
