const yesNo = ["Yes", "No"];
export const memberGroups = [
  ["Basic information", [["name", "Name", "text", true], ["email", "Email", "email", true], ["mobile", "Mobile", "tel"], ["age", "Age", "number"], ["gender", "Gender", ["Male", "Female", "Other"]], ["dob", "Date of birth", "date"], ["height", "Height"], ["weight", "Weight"], ["maritalStatus", "Marital status", ["Never Married", "Divorced", "Widowed"]], ["registerAs", "Register as", ["Self", "Parent", "Sibling", "Relative", "Friend"]]]],
  ["Location and contact", [["nativePlace", "Native place"], ["currentCity", "Current city"], ["district", "District"], ["state", "State"], ["country", "Country"], ["address", "Address", "textarea"]]],
  ["Career and business", [["education", "Education"], ["occupationType", "Occupation", ["Job", "Both", "Private Job", "Government Job", "Business", "Self Employed", "Professional", "Farmer", "Student", "Other"]], ["annualIncome", "Annual income"], ["nri", "NRI", yesNo], ["companyName", "Company"], ["jobType", "Job type", ["Private Job", "Government Job", "Full-time", "Part-time", "Contract", "Freelance", "Internship", "Other"]], ["jobCategory", "Job category"], ["jobLocation", "Job location"], ["jobExperience", "Experience (years)", "number"], ["businessType", "Business type", ["Manufacturing", "Wholesale", "Retail", "IT", "Construction", "Finance", "Healthcare", "Education", "Other"]], ["businessCategory", "Business category"], ["businessLocation", "Business location"], ["businessWebsite", "Business website"], ["yearsInBusiness", "Years in business", "number"], ["numberOfEmployees", "Number of employees", "number"], ["numberOfBranches", "Number of branches", "number"], ["branchLocations", "Branch locations"], ["socialMedia", "Social media"]]],
  ["Family details", [["fatherName", "Father name"], ["fatherOccupation", "Father occupation"], ["motherName", "Mother name"], ["motherOccupation", "Mother occupation"], ["brothersCount", "Brothers", "number"], ["brothersMarried", "Married brothers", "number"], ["sistersCount", "Sisters", "number"], ["sistersMarried", "Married sisters", "number"], ["familyType", "Family type", ["Joint", "Nuclear"]], ["familyStatus", "Family status", ["Middle Class", "Upper Middle Class", "Rich"]]]],
  ["Religion and community", [["religion", "Religion"], ["caste", "Caste"], ["subCaste", "Subcaste"], ["motherTongue", "Mother tongue"], ["kuladeivam", "Kuladeivam"]]],
  ["Horoscope details", [["star", "Star"], ["rashi", "Rashi"], ["lagnam", "Lagnam"], ["gothram", "Gothram"], ["dosha", "Dosha"], ["birthTime", "Birth time", "time"], ["birthPlace", "Birth place"], ["horoscopeAvailable", "Horoscope available", yesNo], ["sevvaiDosham", "Sevvai dosham", yesNo], ["rahuKethuDosham", "Rahu Kethu dosham", yesNo]]],
  ["Partner preferences", [["preferredAgeFrom", "Preferred age from", "number"], ["preferredAgeTo", "Preferred age to", "number"], ["preferredHeight", "Preferred height"], ["preferredEducation", "Preferred education"], ["preferredOccupation", "Preferred occupation"], ["preferredReligion", "Preferred religion"], ["preferredCaste", "Preferred caste"], ["preferredLocation", "Preferred location"], ["preferredStar", "Preferred star"], ["preferredRashi", "Preferred rashi"], ["acceptSevvaiDosham", "Accept Sevvai dosham", yesNo], ["horoscopeMatchingRequired", "Horoscope matching required", yesNo], ["expectations", "Expectations", "textarea"]]],
  ["Assets", [["landAcres", "Land acres"], ["landValue", "Land value"], ["house", "House"], ["vehicle", "Vehicle"], ["otherAssets", "Other assets", "textarea"]]],
  ["Privacy and membership", [["profileVisibility", "Profile visibility", ["Public", "Members Only", "Private"]], ["hideMobile", "Hide mobile", "checkbox"], ["hideIncome", "Hide income", "checkbox"], ["hideCompany", "Hide company", "checkbox"], ["hidePhotos", "Hide photos", "checkbox"], ["isPremium", "Premium membership", "checkbox"], ["gstVerified", "GST verified", "checkbox"], ["businessVerified", "Business verified", "checkbox"]]],
];
export const memberDefaults = { nri: "No", registerAs: "Self", horoscopeAvailable: "No", sevvaiDosham: "No", rahuKethuDosham: "No", acceptSevvaiDosham: "Yes", horoscopeMatchingRequired: "Yes", profileVisibility: "Public" };
export const memberUploads = [["image", "Main photo", false], ["profilePhotos", "Profile photos", true], ["familyPhotos", "Family photos", true], ["officePhotos", "Office photos", true], ["horoscopeFile", "Horoscope file", false]];
export function initialMemberForm(member) {
  return Object.fromEntries(memberGroups.flatMap(([, fields]) => fields.map(([key, , type]) => [key, member?.[key] ?? (type === "checkbox" ? false : memberDefaults[key] ?? "")])));
}
