import { FiEye, FiEdit2, FiTrash2 } from "react-icons/fi";
import { useLanguage } from "../Language";
export default function MemberTable({ members, loading, error, onSelect, onEdit, onDelete }) {
  const { t } = useLanguage();
  return <div className="table-scroll"><table><thead><tr>{["Member", "Age / Gender", "District", "Religion", "Membership"].map(label => <th key={label}>{t(label)}</th>)}{onSelect && <th>{t("Actions")}</th>}</tr></thead><tbody>
    {members.map((m, index) => <tr key={m._id || m.id || index}><td><div className="member-cell">{m.image ? <img className="avatar" src={m.image} alt="" onError={e => { e.currentTarget.style.display = "none"; }} /> : <div className="avatar rose">{(m.name || "M").slice(0, 1).toUpperCase()}</div>}<div><strong>{m.name || t("Unnamed member")}</strong><small>{m.email || t("No email provided")}</small></div></div></td><td>{m.age || "--"}<span className="cell-sub">{t(m.gender || "Not specified")}</span></td><td>{m.district || "--"}</td><td>{m.religion || "--"}</td><td><span className={`badge ${m.isPremium ? "gold" : "neutral"}`}>{t(m.isPremium ? "Premium" : "Standard")}</span></td>{onSelect && <td><div className="row-actions"><button className="icon-button" title={t("View")} aria-label={`${t("View")} ${m.name}`} onClick={() => onSelect(m)}><FiEye /></button>{onEdit && m.role !== "admin" && <button className="icon-button" title={t("Edit member")} aria-label={`${t("Edit member")} ${m.name}`} onClick={() => onEdit(m)}><FiEdit2 /></button>}{onDelete && m.role !== "admin" && <button className="icon-button danger-icon" title={t("Delete member")} aria-label={`${t("Delete member")} ${m.name}`} onClick={() => onDelete(m)}><FiTrash2 /></button>}</div></td>}</tr>)}
    {!members.length && <tr><td colSpan={onSelect ? 6 : 5} className="empty-state">{t(loading ? "Loading profiles..." : error ? "Member records are unavailable." : "No members found.")}</td></tr>}
  </tbody></table></div>;
}
